### ISSUE TITLE
Unable to figure out options for keep_every_point

### ISSUE THREAD

**Issue by advaitambeskar** [mayuso/PNGToSVG#2]
Could you please provide me with details regarding the keep_every_point so that it can be used in multiple ways?

**Comment by mayuso** [comment]
"keep_every_point" is a setting that allows you to keep all the information in the generated SVG file. 

By default, the script converts the image removing redundant data (SVGs are vectors, so if there is straight line of the same color, you don't need to save every pixel), by using "keep_every_point", you tell the software not to remove this data.
