### ISSUE TITLE
Stuck at Calculating edges: 3.61%

### ISSUE THREAD

**Issue by arshad111** [mayuso/PNGToSVG#3]
Hi,
I have run python file using below command.
`python3 pngtosvg.py  original.png`
but it show Converting image: upto 99.92% and after this it will stuck on Calculating edges: 3.61%.
Pleas provide instruction if i forgot.

**Comment by arshad111** [comment]
Hello,

Please check below details
Python version : Python 3.8.5
Library versions : 0.2
![original](https://user-images.githubusercontent.com/15728805/110739579-6f89ce80-8257-11eb-9bd2-da7139134814.png)

**Comment by arshad111** [comment]
Stuck in process with two other png files,please check it
![auc](https://user-images.githubusercontent.com/15728805/110780578-dc6a8c00-828a-11eb-998d-320e5b3d447a.png)
![rect](https://user-images.githubusercontent.com/15728805/110780583-dd9bb900-828a-11eb-929c-c1b2811bfaa2.png)

**Comment by arshad111** [comment]
All above three images converted successfully but its taking long time(approx 30 45 min) to convert.
Please give me instruction about reduce svg file size.
Ex: i have convert one png which has 79 kb but after conversion svg file size is 3.2 mb.

**Comment by mayuso** [comment]
Right now there is no way to configure the call so that it produces a lighter output SVG, sorry.

This project is relatively abandoned, however, if I ever have the time to invest here, I'll try to see why some images take so long, also, if anyone is willing to improve that part, I'll gladly merge any working patch and make a new release.

Thank you :)

**Comment by mayuso** [comment]
Marked as enhancement as we already know this is not really stuck, but just really slow. If someone is willing to put the effort to investigate the long processing times and develop an optimization, I will merge the changes to this project.
